name: Payload Bug
description: Report an issue to help improve payloads provided within this project. Keep in mind - the more information provided here, the more actionable it will become. 
title: "[Payload BUG] write a short description here"

body:
  - type: input
    id: PayloadName
    attributes:
      label: "Payload Title"
      description: "Title of the payload you're experiencing an issue with"
      placeholder: "ex. ExampleTitle"
    validations:
      required: true

  - type: input
    id: PayloadURL
    attributes:
      label: "Payload URL"
      description: "Provide a direct link (URL) to the payload in question within this repo. Not the payload name. "
      placeholder: "ex. https://github.com/hak5/usbrubberducky-payloads/........"
    validations:
      required: true

  - type: textarea
    id: Description
    attributes:
      label: "Description"
      description: "A thorough description of the issue"
      placeholder: 'ex. Here is what I am trying to do; I did X and expected Y to happen but instead...'
    validations:
      required: true

  - type: textarea
    id: Modifications
    attributes:
      label: "Payload Modifications (if any)"
      description: "If any, please list what changes or modifications you have made to the original payload to experience this problem. DO NOT SHARE PRIVATE INFO SUCH AS YOUR DOMAINS OR API KEYS."
      placeholder: "ex. I changed the DEFINE URL example.com to a domain of my own where I'm hosting xyz"
    validations:
      required: false

  - type: textarea
    id: attempts
    attributes:
      label: "Troubleshooting"
      description: "List any steps youve taken trying to troubleshoot or solve the problem you're experiencing "
      placeholder: "ex. I tried A, B, and C, to fix the issue, but..."
    validations:
      required: false

  - type: textarea
    id: causes
    attributes:
      label: "Suspected Cause"
      description: "Could this be because ...?"
      placeholder: "ex. Maybe this is because..."
    validations:
      required: false
      
  - type: textarea
    id: screenshots
    attributes:
      label: "Screenshots or additional information"
      description: "Please add screenshots or extra details without a specific category if applicable"
    validations:
      required: false

  - type: checkboxes
    id: no-duplicate-issues
    attributes:
      label: "Checklist ✅"
      options:
        - label: "I checked and didn't find a similar issue already reported"
          required: true

        - label: "I am using PayloadStudio to encode this payload"
          required: true

        - label: "I made sure to redact any private information in the details shared above"
          required: true

        - label: "I have read the documentation provided by the original payload author and configured the payload (if required)"
          required: true

        - label: "I have confirmed I am deploying this payload with the correct device intended by the original author (Original USB Rubber Ducky vs New USB Rubber Ducky)"
          required: true
          
        - label: "I have confirmed I am deploying this payload on the correct target host intended by the original author (Windows, Mac, Linux, etc)"
          required: true
          
        - label: "I have confirmed the payload is compiled in the correct keyboard language for the target host I'm trying to deploy it on (US, DE, etc)"
          required: true

        - label: "I have actually read the above checkboxes before checking them, including this one, which I have intentionally left unchecked as confirmation of this statement"
          required: false
